function u=getU(alpha,beta,Cd,z,U)
%%%this is wrong.
u=(1/3).*beta.^(-3).*Integrate((c0+c1.*z).^(-3).*(beta.^2.*c1.^2.*(Cd.* ...
  U.^2+6.*beta.*Kint.*(c0+c1.*z).*log(1+exp(1).^(2.*alpha))+Cd.*U.^2.* ...
  tanh(alpha+(-1).*beta.^(-1).*U.^(-1).*z.*(c0+c1.*z)))+Cd.*(c0+c1.*z).* ...
  sech(alpha+(-1).*beta.^(-1).*U.^(-1).*z.*(c0+c1.*z)).^2.*(beta.*c1.*U.*( ...
  2.*c0+3.*c1.*z)+(c0+c1.*z).*(c0+2.*c1.*z).^2.*tanh(alpha+(-1).*beta.^( ...
  -1).*U.^(-1).*z.*(c0+c1.*z)))),z).*log(1+exp(1).^(2.*alpha)).^(-1);
